version: "3.8"

services:
  mongo-express:
    image: mongo-express
    container_name: truthlens-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: TruthlensIsTruthlens
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: truthlens-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TruthlensIsTruthlens

volumes:
  mongo-data:
